### ISSUE TITLE
Issues using stubs

### ISSUE THREAD

**Issue by DBCerigo** [henribru/google-ads-stubs#2] opened 2020-08-27 19:43 UTC
Hi, 

I'd be really to stoked to have typechecking for `google-ads` so interested in getting this working. 

Using versions: 
```
google-ads==5.1.0
google-ads-stubs==3.1.0
```

Currently having the following issues:

### (Partially resolved issue) 1. re `namespace_packages`
With config: 
```
[mypy]
namespace_packages = True
```
getting errors like 
```
some/file.py:2: error: Module 'google.cloud' has no attribute 'bigquery'  [attr-defined]
some/file2.py:9: error: Module 'google.cloud' has no attribute 'storage'  [attr-defined]
```

Making `namespace_packages = False` avoids these errors. 

### Unresolved 2. re standard usage

With an example file like: 
```
from google.ads import google_ads
def get_client() -> google_ads.client.GoogleAdsClient:
    """Get an authenticated Google Ads client."""
   ... [pulling credentials] ...
   return google_ads.client.GoogleAdsClient.load_from_dict(credentials)  
```
gives error: 
```
example/file.py:2: error: Name 'google_ads.client.GoogleAdsClient' is not defined  [name-defined]
example/file.py:5 error: Module has no attribute "client"  [attr-defined]
```

Any ideas?

**Comment by henribru** [comment] 2020-09-26 11:04
Thank you for the report and sorry for the late reply! I have just published a new version that should fix problem number 2. Turns out I was missing some imports: https://github.com/henribru/google-ads-stubs/commit/cb0513a9697778b072ace8e1fa5ec55bd586834c
Initially I actually didn't understand why these imports would lead to `client` being available on `google_ads`, I figured they would only expose something like `google_ads.google.ads.client` (which they also do). I had to look into the Python import system to understand it. Turns out that because modules are only imported once in Python, `google_ads` refers to the same module object everywhere and `import google.ads.google_ads.client` adds `client` to this singleton `google_ads` object. I must admit it seems like a pretty unclear way of them to export the package contents versus something explicit like `from google.ads.google_ads import client`, but now the stubs should conform to this at least.

I'm afraid I don't know what's causing problem number 1, though. Google puts all their packages in the `google` namespace instead of creating entirely different package paths for each library, which has caused some other issues as well. This is why these stubs contain the `py.typed` with "partial" in it, it declares that these stubs are not designed to cover everything in the `google` package. I'm not sure if it's this that's not working in combination with `namespace_packages` or something else. Do these errors only happen if you use my stubs?

**Comment by DBCerigo** [comment] 2020-09-26 11:15
Glad it was of some help. Yep, I concur that the `google_ads` package and Google's style of producing python packages specifically when it comes to instantiating their module path structures is pretty complex...!

I'm see when I next get a moment to give these stubs another shot let you know re the problem 1 then. 

Thanks.

**Comment by henribru** [comment] 2021-03-07 09:37
I looked into problem 1 a bit and I'm unable to reproduce it. I ran Mypy over this file with and without `--namespace-packages`:
```
from google.cloud import bigquery
from google.cloud import storage
from google.ads import google_ads
```
The behavior is the same in both cases, the following error:
```
namespace.py:1: error: Skipping analyzing 'google.cloud': found module but no type hints or library stubs
namespace.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```
This is the expected error for importing something that doesn't have stubs. If I add `--ignore-missing-imports` I get no errors in either case. It's possible that you ran into issue that's been fixed in a later version of Mypy, I tested it using 0.812. I'll close this issue now, but if you experience a similar issue again, let me know and I'll reopen it and investigate further.

**Closed** 2021-03-07 09:39 UTC
